

DELETE FROM dbo.[user];
DELETE FROM dbo.[recipe];

SET IDENTITY_INSERT [dbo].[user] ON;

INSERT INTO [dbo].[user] (
    [user_id],
    [first_name],
    [last_name],
    [username],
    [password],
    [two_factor_auth_enabled],
    [two_factor_auth_key]
)
VALUES
(1,'Giada','De Laurentiis','giada','$2a$12$hy2lpZqVp.gvng5Fq0u4DOuPQq/VLCfdHjyOzhSWhJPwz7hSCGpRy',NULL,NULL),
(2,'Gordon','Ramsay','gordon','$2a$12$hy2lpZqVp.gvng5Fq0u4DOuPQq/VLCfdHjyOzhSWhJPwz7hSCGpRy',NULL,NULL)
;

SET IDENTITY_INSERT [dbo].[user] OFF;
SET IDENTITY_INSERT [dbo].[recipe] ON;
INSERT INTO dbo.[recipe](
    [recipe_id],
    [title],
    [description],
    [ingredients],
    [directions],
    [user_id]
)
VALUES
(1,'leek swelling','rock unchewed microwave','Bacon ipsum dolor amet bacon biltong brisket sirloin kielbasa,hock beef landjaeger boudin alcatra,sausage beef beef ribs pancetta pork chop doner short ribs,brisket alcatra shankle pork chop, turducken picanha,Venison doner leberkas turkey ball tip tongue','Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.,Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.',1),
(2,'distribution lusty','diaphragm homebound TOP','Bacon ipsum dolor amet bacon biltong brisket sirloin kielbasa,hock beef landjaeger boudin alcatra,sausage beef beef ribs pancetta pork chop doner short ribs,brisket alcatra shankle pork chop, turducken picanha,Venison doner leberkas turkey ball tip tongue','Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.,Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.',1),
(3,'okra crumpled','clutch faucal gold','Bacon ipsum dolor amet bacon biltong brisket sirloin kielbasa,hock beef landjaeger boudin alcatra,sausage beef beef ribs pancetta pork chop doner short ribs,brisket alcatra shankle pork chop, turducken picanha,Venison doner leberkas turkey ball tip tongue','Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.,Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.',2),
(4,'craftsman roseless','pink leachy place','Bacon ipsum dolor amet bacon biltong brisket sirloin kielbasa,hock beef landjaeger boudin alcatra,sausage beef beef ribs pancetta pork chop doner short ribs,brisket alcatra shankle pork chop, turducken picanha,Venison doner leberkas turkey ball tip tongue','Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.,Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.',2),
(5,'lunge raploch','nylon hatching honey','Bacon ipsum dolor amet bacon biltong brisket sirloin kielbasa,hock beef landjaeger boudin alcatra,sausage beef beef ribs pancetta pork chop doner short ribs,brisket alcatra shankle pork chop, turducken picanha,Venison doner leberkas turkey ball tip tongue','Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.,Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.',2),
(6,'toenail measly','palm craggy war','Bacon ipsum dolor amet bacon biltong brisket sirloin kielbasa,hock beef landjaeger boudin alcatra,sausage beef beef ribs pancetta pork chop doner short ribs,brisket alcatra shankle pork chop, turducken picanha,Venison doner leberkas turkey ball tip tongue','Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.,Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.',2),
(7,'rain matey','state nuptial expansion','Bacon ipsum dolor amet bacon biltong brisket sirloin kielbasa,hock beef landjaeger boudin alcatra,sausage beef beef ribs pancetta pork chop doner short ribs,brisket alcatra shankle pork chop, turducken picanha,Venison doner leberkas turkey ball tip tongue','Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.,Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.',1),
(8,'turnip mitered','roll lupine acoustic','Bacon ipsum dolor amet bacon biltong brisket sirloin kielbasa,hock beef landjaeger boudin alcatra,sausage beef beef ribs pancetta pork chop doner short ribs,brisket alcatra shankle pork chop, turducken picanha,Venison doner leberkas turkey ball tip tongue','Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.,Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.',2),
(9,'ski unturned','jail burry cycle','Bacon ipsum dolor amet bacon biltong brisket sirloin kielbasa,hock beef landjaeger boudin alcatra,sausage beef beef ribs pancetta pork chop doner short ribs,brisket alcatra shankle pork chop, turducken picanha,Venison doner leberkas turkey ball tip tongue','Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.,Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor IN reprehenderit IN voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt IN culpa qui officia deserunt mollit anim id est laborum.',1)
;

SET IDENTITY_INSERT [dbo].[recipe] OFF;
GO
;